<?php

namespace Tests;

use App\Models\Task;
use App\Models\TodoList;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->withoutExceptionHandling();
    }

    public function createTodoList($arg = [])
    {
        return TodoList::factory()->create($arg);
    }

    public function createTask($arg = [])
    {
        return Task::factory()->create($arg);
    }
}
